import "./globals.css";
import Header from "@/app/components/frame/Header";
import Main from "@/app/components/frame/Main";
import Footer from "@/app/components/frame/Footer";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <Main children={children}/>
        <Footer/>
        </body>
        </html>
    );
}

